-- EROSS Agenda: ESQUEMA PROPUESTO para NUEVA base Neon exclusivamente
-- NO representa un pg_dump del origen. Verificar constraints e índices faltantes.
-- Ejecutar sólo en soft-lake-14045662 / eross_agenda, después de revisión.
BEGIN;
CREATE TABLE IF NOT EXISTS agenda_companies(id uuid PRIMARY KEY,name text NOT NULL,slug text,timezone text NOT NULL DEFAULT 'America/Costa_Rica',active boolean DEFAULT true,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_users(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES agenda_companies(id),name text NOT NULL,email text,role text,active boolean DEFAULT true,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_locations(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES agenda_companies(id),name text NOT NULL,address text,timezone text,active boolean DEFAULT true,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_clients(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES agenda_companies(id),name text NOT NULL,phone text,email text,source text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_appointment_types(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES agenda_companies(id),name text NOT NULL,duration_min integer NOT NULL,modality text,color text,buffer_before_min integer DEFAULT 0,buffer_after_min integer DEFAULT 0,active boolean DEFAULT true,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_availability_rules(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES agenda_companies(id),weekday integer NOT NULL,active boolean DEFAULT true,all_day boolean DEFAULT false,slots jsonb NOT NULL DEFAULT '[]'::jsonb,user_id uuid REFERENCES agenda_users(id),location_id uuid REFERENCES agenda_locations(id));
CREATE TABLE IF NOT EXISTS agenda_blocks(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES agenda_companies(id),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,reason text,user_id uuid REFERENCES agenda_users(id),location_id uuid REFERENCES agenda_locations(id));
CREATE TABLE IF NOT EXISTS agenda_appointments(id uuid PRIMARY KEY,company_id uuid NOT NULL REFERENCES agenda_companies(id),client_id uuid REFERENCES agenda_clients(id),appointment_type_id uuid REFERENCES agenda_appointment_types(id),responsible_user_id uuid REFERENCES agenda_users(id),location_id uuid REFERENCES agenda_locations(id),external_crm_lead_id text,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,reserved_starts_at timestamptz NOT NULL,reserved_ends_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'pending',modality text,source text,comments text,confirmation_channel text,reminder_minutes integer,tags text[] DEFAULT '{}',color text,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_appointment_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES agenda_companies(id),appointment_id uuid REFERENCES agenda_appointments(id),event_type text NOT NULL,payload jsonb DEFAULT '{}'::jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_integration_outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES agenda_companies(id),appointment_id uuid REFERENCES agenda_appointments(id),event_type text NOT NULL,destination text NOT NULL,payload jsonb DEFAULT '{}'::jsonb,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS agenda_booking_settings(company_id uuid PRIMARY KEY REFERENCES agenda_companies(id),slot_interval_min integer NOT NULL DEFAULT 30,min_notice_min integer NOT NULL DEFAULT 120,updated_at timestamptz DEFAULT now());
COMMIT;
