import {useEffect,useMemo,useState} from "react";
const palette={navy:"#091a2c",dark:"#10283f",gold:"#c59a42",soft:"#f2f5f8",border:"#e4eaf0",muted:"#738298"};
const titleMap={"appointment.created":"Cita creada","appointment.confirmed":"Cita confirmada","appointment.rescheduled":"Cita reprogramada","appointment.cancelled":"Cita cancelada","appointment.attended":"Cita atendida","appointment.no_show":"No asistió","qa.delivery.test":"Prueba HTTP QA"};
const labels={pending:"Pendiente",retry:"Reintento",delivered:"Entregada",failed:"Fallida",processing:"Procesando"};
const hues={pending:["#fff5df","#93600b"],retry:["#fff0de","#b45309"],delivered:["#e6f7ee","#12764a"],failed:["#fceaea","#aa293b"],processing:["#e8f2ff","#2563a5"]};
const dt=x=>x?new Date(x).toLocaleString("es-CR",{dateStyle:"medium",timeStyle:"short"}):"—";
const advice={
 failed:{title:"Entrega fallida",steps:["Revisar el último error en el historial.","Verificar que el receptor esté disponible y que las credenciales sigan vigentes.","Confirmar que el receptor acepte identificadores repetidos antes de reintentar."],action:"Revisión técnica requerida"},
 stuck:{title:"Procesamiento interrumpido",steps:["Verificar si la ejecución del procesador finalizó inesperadamente.","Comprobar logs del servidor y disponibilidad de la base de datos.","Dejar que venza el bloqueo temporal antes de una nueva ejecución."],action:"Inspeccionar ejecución"},
 overdue:{title:"Señales pendientes por más de 24 horas",steps:["Comprobar si el envío está desactivado intencionalmente en QA.","Verificar la configuración del receptor y el programador.","Priorizar las señales más antiguas una vez habilitado el receptor."],action:"Revisar configuración"},
 retry:{title:"Entrega pendiente de reintento",steps:["Leer el error de la última entrega.","Si aparece HTTP 401 o 403, revisar autenticación y protección del receptor.","Si aparece HTTP 5xx o timeout, revisar la disponibilidad del servicio; esperar el siguiente intento programado."],action:"Esperar o investigar"},
 backlog:{title:"Acumulación de eventos",steps:["Comprobar la frecuencia del procesador y cuántas señales procesa por ejecución.","Buscar errores repetitivos antes de aumentar la frecuencia.","Evaluar capacidad y límites del receptor."],action:"Evaluar capacidad"}
};
const card={background:"#fff",border:"1px solid "+palette.border,borderRadius:18,padding:22,boxShadow:"0 5px 22px rgba(16,40,63,.035)"};
export default function EventHubQA(){
 const [report,setReport]=useState(null),[auth,setAuth]=useState("loading"),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[filter,setFilter]=useState("all"),[search,setSearch]=useState(""),[refreshing,setRefreshing]=useState(false);
 const refresh=async()=>{setRefreshing(true);try{const r=await fetch("/api/agenda/event-hub",{cache:"no-store"});if(r.status===401||r.status===403){setAuth("no");return}if(!r.ok)throw Error("Respuesta "+r.status);setReport(await r.json());setAuth("yes")}catch(e){setAuth("error");setResult({error:"No fue posible actualizar: "+e.message})}finally{setRefreshing(false)}};
 useEffect(()=>{refresh()},[]);
 const run=async()=>{setBusy(true);setResult(null);try{const r=await fetch("/api/agenda/event-hub-process",{method:"POST"});const j=await r.json();setResult({http:r.status,...j});await refresh()}catch(e){setResult({error:String(e)})}finally{setBusy(false)}};
 const totals=Object.fromEntries((report?.summary||[]).map(x=>[x.delivery_status,Number(x.total)]));
 const total=Object.values(totals).reduce((a,b)=>a+b,0);
 const latest=useMemo(()=>(report?.latest||[]).filter(x=>(filter==="all"||x.delivery_status===filter)&&[x.event_type,x.id,x.delivery_status].join(" ").toLowerCase().includes(search.trim().toLowerCase())),[report,filter,search]);
 const pill=s=>{const [bg,fg]=hues[s]||["#edf0f3","#536579"];return <span style={{background:bg,color:fg,padding:"5px 10px",borderRadius:99,fontWeight:750,fontSize:12,whiteSpace:"nowrap"}}>{labels[s]||s}</span>};
 const button={border:0,borderRadius:11,padding:"12px 17px",fontWeight:750,cursor:"pointer"};
 return <main style={{fontFamily:"Inter,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif",minHeight:"100vh",background:palette.soft,color:palette.dark}}>
 <header style={{background:palette.navy,color:"white",padding:"20px max(24px, calc((100vw - 1150px)/2))",display:"flex",alignItems:"center",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}>
 <div style={{display:"flex",alignItems:"center",gap:13}}><div style={{width:45,height:45,border:"2px solid "+palette.gold,borderRadius:13,color:palette.gold,display:"grid",placeItems:"center",fontSize:24,fontWeight:900}}>E</div><div><div style={{fontWeight:850,fontSize:21}}>EROSS <span style={{color:palette.gold}}>Event Hub</span></div><div style={{fontSize:12,color:"#abc0cf"}}>Centro de integraciones · Laboratorio QA</div></div></div>
 <a href="/agenda-master-review" style={{color:"#e5edf3",textDecoration:"none",fontWeight:650,fontSize:13}}>← Volver a Agenda</a></header>
 <div style={{maxWidth:1150,margin:"0 auto",padding:"33px 20px 65px"}}>
 <div style={{display:"flex",gap:18,alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",marginBottom:25}}><div><div style={{fontSize:12,color:"#986d22",letterSpacing:2,fontWeight:800}}>MONITOREO DE INTEGRACIONES</div><h1 style={{fontSize:"clamp(25px,3vw,37px)",margin:"9px 0 7px"}}>Estado de las señales</h1><div style={{color:palette.muted}}>Vista de pruebas · Envíos de citas reales desactivados</div></div><button disabled={refreshing} onClick={refresh} style={{...button,background:"white",color:palette.dark,border:"1px solid "+palette.border}}>{refreshing?"Actualizando...":"↻ Actualizar datos"}</button></div>
 {auth==="loading"?<div style={card}>Conectando de forma segura...</div>:auth==="no"?<div style={card}><h3>Tu sesión de QA no está activa</h3><p>Entrá a EROSS Agenda desde este mismo dominio y regresá a este panel.</p><a href="/agenda-master-review">Abrir inicio de sesión →</a></div>:auth==="error"?<div style={card}>No se pudo consultar la información. Usá «Actualizar datos» para reintentar.</div>:<>
 <section aria-label="Alertas de integración" style={{...card,marginBottom:19,borderLeft:"5px solid "+((report?.alerts?.notices||[]).some(x=>x.level==="critical")?"#b72c3e":(report?.alerts?.notices||[]).length?"#c59a42":"#18794e")}}>
 <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,flexWrap:"wrap",marginBottom:12}}><div><h2 style={{margin:"0 0 5px",fontSize:19}}>Alertas de integraciones</h2><span style={{color:palette.muted,fontSize:13}}>Detección automática al consultar el panel · Umbral de antigüedad: 24 horas</span></div><strong style={{color:(report?.alerts?.notices||[]).length?"#a87919":"#18794e"}}>{(report?.alerts?.notices||[]).length} alertas</strong></div>
 {(report?.alerts?.notices||[]).length===0?<div style={{color:"#18794e",fontWeight:700}}>✓ No hay alertas activas en este momento.</div>:<div style={{display:"grid",gap:9}}>{report.alerts.notices.map(x=><div key={x.code} style={{background:x.level==="critical"?"#fdf0f1":"#fff7e7",borderRadius:11,padding:"13px 15px",display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",flexWrap:"wrap"}}><div><strong style={{color:x.level==="critical"?"#a52c3e":"#8c5c11"}}>{x.level==="critical"?"Atención crítica":"Advertencia"}</strong><div style={{fontSize:13,marginTop:4}}>{x.message}</div></div><strong style={{fontSize:22}}>{x.count}</strong></div>)}</div>}
 <div style={{fontSize:12,color:palette.muted,marginTop:12}}>En QA algunas señales antiguas permanecen pendientes intencionalmente; las alertas indican su estado, no una interrupción de producción.</div></section>
 <section style={{...card,marginBottom:19}}><h2 style={{fontSize:19,margin:"0 0 5px"}}>Centro de resolución</h2><p style={{margin:"0 0 15px",color:palette.muted,fontSize:13}}>Recomendaciones orientativas según las alertas activas. No realizan cambios ni reenvíos automáticamente.</p>
 {(report?.alerts?.notices||[]).length===0?<div style={{fontSize:13,color:"#18794e"}}>No hay incidentes activos que requieran una recomendación.</div>:<div style={{display:"grid",gap:11}}>{report.alerts.notices.map(n=>{const a=advice[n.code];return <details key={n.code} style={{border:"1px solid "+palette.border,borderRadius:12,padding:"14px 16px",background:"#fbfcfd"}}><summary style={{cursor:"pointer",fontWeight:750,color:palette.dark}}>{a?.title||n.message} · {n.count} señales</summary><div style={{paddingTop:13,fontSize:13,color:palette.dark}}><div style={{color:palette.muted,marginBottom:8}}>Acción sugerida: <strong>{a?.action||"Revisar alerta"}</strong></div><ol style={{paddingLeft:21,lineHeight:1.8,margin:"5px 0"}}>{(a?.steps||[]).map((step,i)=><li key={i}>{step}</li>)}</ol></div></details>})}</div>}
 </section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:15,marginBottom:19}}>
 {[["Total de señales",total,"#10283f"],["Pendientes",totals.pending||0,"#a87919"],["Entregadas",totals.delivered||0,"#18794e"],["Reintentos",totals.retry||0,"#b45309"],["Fallidas",totals.failed||0,"#b72c3e"]].map(([t,n,color])=><div key={t} style={{...card,borderTop:"4px solid "+color}}><div style={{fontSize:13,fontWeight:650,color:palette.muted}}>{t}</div><div style={{fontWeight:850,fontSize:37,color,marginTop:11}}>{n}</div></div>)}</section>
 <section style={{...card,marginBottom:19,display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 5px",fontSize:18}}>Salud de la integración</h2><div style={{color:palette.muted,fontSize:13}}>{(totals.failed||0)>0?"Hay señales fallidas que requieren revisión":(totals.retry||0)>0?"Hay entregas en espera de reintento":"Sin fallos activos"} · Destino: EROSS CRM</div></div><div>{(totals.failed||0)>0?pill("failed"):(totals.retry||0)>0?pill("retry"):pill("delivered")}</div></section>
 <section style={{...card,marginBottom:19}}><div style={{display:"flex",justifyContent:"space-between",gap:15,flexWrap:"wrap",alignItems:"center",marginBottom:15}}><div><h2 style={{margin:"0 0 5px",fontSize:19}}>Historial reciente</h2><span style={{fontSize:13,color:palette.muted}}>Últimas 30 señales · Sin datos personales</span></div><div style={{display:"flex",gap:9,flexWrap:"wrap"}}><select aria-label="Filtrar por estado" value={filter} onChange={e=>setFilter(e.target.value)} style={{padding:11,borderRadius:10,border:"1px solid "+palette.border,background:"white"}}><option value="all">Todos los estados</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input aria-label="Buscar evento" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar evento..." style={{padding:11,borderRadius:10,border:"1px solid "+palette.border,maxWidth:190}}/></div></div>
 <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13,textAlign:"left"}}><thead><tr style={{color:palette.muted,borderBottom:"1px solid "+palette.border}}>{["Evento","Creación","Estado","Intentos","Próximo intento / Entrega"].map(x=><th key={x} style={{padding:"12px 10px"}}>{x}</th>)}</tr></thead><tbody>{latest.map(x=><tr key={x.id} style={{borderBottom:"1px solid "+palette.border}}><td style={{padding:"14px 10px"}}><strong>{titleMap[x.event_type]||x.event_type}</strong><div style={{fontSize:11,color:palette.muted,marginTop:4}}>{x.event_type}</div>{x.last_error&&<div style={{fontSize:11,color:"#a33b36",marginTop:6}}>Error: {x.last_error}</div>}</td><td style={{padding:"14px 10px",whiteSpace:"nowrap"}}>{dt(x.created_at)}</td><td style={{padding:"14px 10px"}}>{pill(x.delivery_status)}</td><td style={{padding:"14px 10px"}}>{x.attempt_count}</td><td style={{padding:"14px 10px",whiteSpace:"nowrap"}}>{dt(x.delivered_at||(x.delivery_status==="retry"?x.next_attempt_at:null))}</td></tr>)}{!latest.length&&<tr><td colSpan="5" style={{padding:30,textAlign:"center",color:palette.muted}}>No hay señales para este filtro</td></tr>}</tbody></table></div></section>
 <section style={{...card,background:"#fffaf0",borderColor:"#ead9b7"}}><h2 style={{margin:"0 0 7px",fontSize:19}}>Banco de pruebas HTTP</h2><p style={{color:"#74664e",fontSize:13,lineHeight:1.6}}>Esta acción procesa únicamente eventos ficticios <code>qa.delivery.test</code>. No envía las señales de citas reales. La recepción sigue en el laboratorio QA.</p><button onClick={run} disabled={busy} style={{...button,background:palette.gold,color:"#fff"}}>{busy?"Procesando...":"Probar entrega HTTP · QA"}</button>{result&&<div style={{marginTop:16,padding:14,background:"white",borderRadius:11,fontSize:13}}>{result.error?<strong style={{color:"#ab3042"}}>{result.error}</strong>:<div><strong>HTTP {result.http} · {result.ok?"Solicitud procesada":"Revisar resultado"}</strong><div style={{marginTop:8,display:"flex",gap:16,flexWrap:"wrap"}}><span>Reclamadas: {result.claimed??0}</span><span>Entregadas: {result.delivered??0}</span><span>Reintentos: {result.retries??0}</span><span>Fallidas: {result.failed??0}</span></div></div>}</div>}</section>
 </>}
 <footer style={{marginTop:24,color:palette.muted,fontSize:12}}>EROSS Event Hub · Entorno aislado de QA · No representa entregas a un CRM en producción.</footer>
 </div></main>;
}
